import { useState } from 'react';
import { sections, viewFor, type primaryEntry } from '../pages';
import type { Dashboard } from '../pages/dashboard';

type Entry = NonNullable<ReturnType<typeof primaryEntry>>;

/** The approved design's line icons, drawn in the text colour of the entry they sit in. */
const paths: Record<string, string> = {
  work: 'M3 6a2 2 0 012-2h14a2 2 0 012 2v12a2 2 0 01-2 2H5a2 2 0 01-2-2zM3 9h18M9 20V9',
  workers: 'M9 11.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7zM2.5 20c.8-3.6 3.4-5.5 6.5-5.5s5.7 1.9 6.5 5.5M16 4.8a3.5 3.5 0 010 6.4M18.5 14.8c1.6.8 2.6 2.6 3 5.2',
  shipped: 'M4 12.5l5 5L20 6.5',
  tests: 'M9 3h6M10 3v6l-5.5 9.5A1.7 1.7 0 006 21h12a1.7 1.7 0 001.5-2.5L14 9V3',
  insights: 'M4 20V10M10 20V4M16 20v-7M22 20H2',
  settings: 'M12 15a3 3 0 100-6 3 3 0 000 6zM12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1',
};
export const NavIcon = ({ name }: { name: string }) => <svg className="nav-icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d={paths[name] ?? paths.work}/></svg>;

/**
 * The one navigation (GY-161): Work, Workers, Shipped, Tests (planned, GY-162), Insights and
 * Settings, generated by web/main.tsx from the view registry, then the repository, how fresh the
 * data is, the short guide and sign-out. On a phone it folds into a menu button.
 */
export default function Sidebar({ entries, dashboard }: { entries: (Entry | null)[]; dashboard: Dashboard }) {
  const { view, setView, setSelected, connected, lastUpdated, status, signOut } = dashboard;
  const [open, setOpen] = useState(false);
  const go = (id: string) => { setSelected(null); setView(id); setOpen(false); };
  const current = viewFor(view).section;
  const actor = status?.actor;
  return <aside className={open ? 'sidebar open' : 'sidebar'}><div className="sidebar-inner">
    <div className="sidebar-head">
      <div className="brand"><img className="mark" src="/graphyard-symbol.svg" alt="" width="26" height="26"/> graphyard</div>
      <button type="button" className="menu-button" aria-label="Menu" aria-expanded={open} onClick={() => setOpen(value => !value)}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button>
    </div>
    <nav className="primary-nav" aria-label="Primary">{sections.map(section => {
      if ('planned' in section) return <span key={section.id} className="nav planned" aria-disabled="true" data-nav={section.id} title={`Planned in ${section.planned}`}><NavIcon name={section.icon}/><span>{section.label}</span><small>planned</small></span>;
      const entry = entries.find(candidate => candidate?.id === section.id);
      if (!entry) return null;
      const active = current === entry.id;
      return <button key={entry.id} type="button" data-nav={entry.id} className={active ? 'nav active' : 'nav'} aria-current={active ? 'page' : undefined} onClick={() => go(entry.view.id)}><NavIcon name={section.icon}/><span>{entry.label}</span></button>;
    })}</nav>
    <div className="sidebar-bottom">
      {status?.repository && <span className="mono repository">{status.repository}</span>}
      <span className="connection"><span className={`dot ${connected ? 'live' : ''}`}/>{connected ? `Live · updated ${lastUpdated ?? 'now'}` : `Disconnected · last updated ${lastUpdated ?? 'never'}`}</span>
      {actor && <span className="signed-in" title="Signed in as">{actor.id} · {actor.role}</span>}
      <span className="sidebar-links"><button type="button" className="text-button" onClick={() => go('guide')}>Help</button><a className="docs-link" href="/docs">Documentation ↗</a><button type="button" className="text-button" onClick={signOut}>Sign out</button></span>
    </div>
  </div></aside>;
}
