import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
// @ts-expect-error Dependency-free documentation script.
import { budget, corpusPaths, countWords, measure } from '../scripts/docs-budget.mjs';

/**
 * Length is a defect in guides that are read under time pressure, so the corpus has a word
 * budget and a per-page cap, and this is the inventory `unit:docs-word-budget` judges.
 */
const root = fileURLToPath(new URL('..', import.meta.url));

test('unit:docs-word-budget the documentation fits the total budget and no page exceeds the per-page cap', () => {
  const report = measure(root);
  assert.deepEqual(report.failures, [], report.failures.join('\n'));
  assert.ok(report.total <= budget.total, `documentation is ${report.total} words; the budget is ${budget.total}`);
  for (const page of report.pages) assert.ok(page.words <= budget.page, `${page.path} is ${page.words} words; the cap is ${budget.page}`);
  // The budget is a real cut, not a restated baseline.
  assert.ok(report.total <= budget.baseline * 0.3, `${report.reduction}% smaller than the ${budget.baseline}-word baseline; at least 70% is required`);
});

test('unit:docs-word-budget the corpus is every page the criterion names and the count is wc -w', () => {
  const paths = corpusPaths(root);
  assert.equal(paths[0], 'AGENTS.md');
  for (const required of ['docs/README.md', 'docs/glossary.md', 'docs/protocol.md', 'docs/protocol/roles.md'])
    assert.ok(paths.includes(required), `the corpus covers ${required}`);
  assert.ok(paths.every((path: string) => path === 'AGENTS.md' || path.startsWith('docs/')), 'only AGENTS.md and docs/ are budgeted');
  assert.ok(paths.some((path: string) => path.startsWith('docs/history/')), 'docs/ is read recursively');
  // Words are whitespace-separated tokens, exactly as the baseline was measured.
  assert.equal(countWords('one two  three\nfour\t five '), 5);
  assert.equal(countWords('```sh\nnpm test\n```'), 4);
  assert.equal(countWords('   '), 0);
});

test('unit:docs-word-budget every page opens with one sentence naming its reader and the decision it supports', () => {
  const failures: string[] = [];
  for (const path of corpusPaths(root)) {
    const text = readFileSync(`${root}${path}`, 'utf8');
    // Generated index pages carry the generator's own prose; AGENTS.md is rendered into a
    // managed repository rather than read as a guide.
    if (path === 'AGENTS.md' || text.includes('<!-- generated by scripts/check-docs.mjs')) continue;
    const body = text.split('\n').filter(line => !line.startsWith('<!--'));
    const heading = body.findIndex(line => line.startsWith('# '));
    if (heading < 0) { failures.push(`${path}: no title`); continue; }
    const opener = body.slice(heading + 1).find(line => line.trim().length > 0) ?? '';
    if (!/^For [a-z]/.test(opener.trim())) failures.push(`${path}: the first line after the title must start "For <reader>:", not ${JSON.stringify(opener.slice(0, 40))}`);
    else if (opener.trim().split(/\s+/).length > 45) failures.push(`${path}: the opening sentence is ${opener.trim().split(/\s+/).length} words; keep it to one sentence`);
  }
  assert.deepEqual(failures, [], failures.join('\n'));
});
