import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFile, execFileSync } from 'node:child_process';
import { createServer } from 'node:http';
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { classifyScope, regressionRefusals } from '../src/regression-guard.js';
import { parseGeneratedFiles } from '../src/generated-files.js';
import { attributeConflicts, hasConflictMarkers, managedServerUrl, parseGeneratedManifest, regenerateManagedBlocks } from '../src/sync.js';
import { managedInstructions } from '../src/repository-setup.js';
import { managedMasterInstructions } from '../src/master.js';
import type { ScopeFile, Work } from '../src/model.js';
import { readMasterGuide } from './helpers/master-guide.js';
import { temporaryDirectory } from './helpers/temp-dirs.js';

const exec = promisify(execFile);
const repositoryRoot = fileURLToPath(new URL('..', import.meta.url));
const launcher = join(repositoryRoot, 'bin/graphyard.mjs');
const checkDocs = join(repositoryRoot, 'scripts/check-docs.mjs');
const file = (path: string, status: ScopeFile['status'] = 'modified', overrides: Partial<ScopeFile> = {}): ScopeFile => ({ path, status, sha: 'new', additions: 3, deletions: 2, binary: false, baseSha: 'old', ...overrides });

test('integration:generated-index-no-conflict — the regression guard classifies a regenerated index as generated only when the deployment declares it, and still refuses its deletion', () => {
  const generated = ['docs/README.md', 'docs/protocol.md'];
  const findings = classifyScope(['src/cli/'], [file('docs/README.md'), file('docs/protocol.md', 'added', { baseSha: null }), file('docs/protocol.md', 'removed', { sha: null }), file('docs/coordination.md')], generated);
  assert.deepEqual(findings.map(finding => [finding.path, finding.kind, finding.refused]), [
    ['docs/README.md', 'generated', false], ['docs/protocol.md', 'generated', false], ['docs/protocol.md', 'deleted', true], ['docs/coordination.md', 'rewritten', true]]);
  assert.deepEqual(classifyScope(['src/cli/'], [file('docs/README.md')], []).map(finding => finding.kind), ['rewritten'], 'without a declaration the out-of-scope rule is unchanged');
  const work = { key: 'GY-1', plannedFiles: ['src/cli/'] } as Work;
  assert.deepEqual(regressionRefusals(work, { scopeFiles: [file('docs/README.md')] }, [], generated), []);
  assert.match(regressionRefusals(work, { scopeFiles: [file('docs/README.md')] }, [], [])[0], /outside its planned files/);
  assert.deepEqual(parseGeneratedFiles(' docs/README.md, docs/protocol.md ,docs/README.md'), ['docs/README.md', 'docs/protocol.md']);
  assert.deepEqual(parseGeneratedFiles(undefined), []);
  for (const bad of ['/docs/README.md', 'docs/', 'docs/*.md', '../README.md', 'docs\\README.md']) assert.throws(() => parseGeneratedFiles(bad), /exact repository-relative files/, bad);
  assert.deepEqual(parseGeneratedManifest('{"generated":["docs/README.md"],"regenerate":"node scripts/check-docs.mjs --write"}'), { files: ['docs/README.md'], regenerate: ['node', 'scripts/check-docs.mjs', '--write'] });
  assert.equal(parseGeneratedManifest('{"generated":[]}'), null); assert.equal(parseGeneratedManifest('not json'), null);
});

test('integration:generated-index-no-conflict — this repository declares docs/README.md and docs/protocol.md generated, renders them in full, and refuses a stale or missing copy', async () => {
  const manifest = parseGeneratedManifest(execFileSync(process.execPath, [checkDocs, '--manifest'], { cwd: repositoryRoot, encoding: 'utf8' }))!;
  assert.deepEqual(manifest.files, ['docs/protocol.md', 'docs/README.md']);
  for (const path of manifest.files) {
    const content = await readFile(join(repositoryRoot, path), 'utf8');
    assert.match(content.split('\n').slice(0, 2).join('\n'), /<!-- generated by scripts\/check-docs\.mjs; do not edit/, `${path} says it is generated`);
    assert.doesNotMatch(content, /<!-- index:/, `${path} carries no hand-merged index block`);
  }
  // The deployment variable and the sync manifest must name the same files.
  const coordination = await readFile(join(repositoryRoot, 'docs/coordination.md'), 'utf8');
  assert.ok(coordination.includes(`GRAPHYARD_GENERATED_FILES=${manifest.files.join(',')}`), 'docs/coordination.md states the deployment value that matches the manifest');
  // A copy of the docs alone: links to examples and workflows dangle there, so only the
  // generated-index verdicts are read from the checker's output.
  const copy = await temporaryDirectory('docs-copy');
  try {
    await exec('cp', ['-r', join(repositoryRoot, 'docs'), join(repositoryRoot, 'README.md'), copy]);
    await mkdir(join(copy, 'scripts')); await copyFile(checkDocs, join(copy, 'scripts/check-docs.mjs'));
    const verdicts = (...args: string[]) => exec(process.execPath, ['scripts/check-docs.mjs', ...args], { cwd: copy }).then(result => result.stdout + result.stderr, (error: any) => `${error.stdout}${error.stderr}`).then(output => output.split('\n').filter(line => /generated index|Regenerated/.test(line)));
    assert.deepEqual(await verdicts(), []);
    await writeFile(join(copy, 'docs/protocol.md'), (await readFile(join(copy, 'docs/protocol.md'), 'utf8')).replace('## Agent protocol', '## Agent protocol\n\n- hand-added line'));
    assert.deepEqual(await verdicts(), ['docs/protocol.md: the generated index is stale; run npm run docs:check -- --write']);
    await rm(join(copy, 'docs/README.md'));
    assert.deepEqual(await verdicts(), ['docs/protocol.md: the generated index is stale; run npm run docs:check -- --write', 'docs/README.md: the generated index is missing; run npm run docs:check -- --write']);
    assert.deepEqual(await verdicts('--write'), ['Regenerated docs/protocol.md', 'Regenerated docs/README.md']);
    assert.deepEqual(await verdicts(), []);
    for (const path of manifest.files) assert.equal(await readFile(join(copy, path), 'utf8'), await readFile(join(repositoryRoot, path), 'utf8'), `--write is deterministic for ${path}`);
  } finally { await rm(copy, { recursive: true, force: true }); }
});

// A small documented repository: the docs generator, one page per index section, the managed
// AGENTS.md blocks, and an origin the branch under test syncs against.
async function fixtureRepository() {
  const root = await temporaryDirectory('sync');
  const origin = join(root, 'origin.git'), main = join(root, 'main'), branch = join(root, 'branch');
  execFileSync('git', ['init', '-q', '--bare', '-b', 'main', origin]);
  execFileSync('git', ['clone', '-q', origin, main], { stdio: 'ignore' });
  const git = (cwd: string, ...args: string[]) => execFileSync('git', ['-C', cwd, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  for (const cwd of [main]) { git(cwd, 'config', 'user.email', 't@example.com'); git(cwd, 'config', 'user.name', 'T'); }
  await mkdir(join(main, 'scripts')); await copyFile(checkDocs, join(main, 'scripts/check-docs.mjs'));
  await mkdir(join(main, 'docs/protocol'), { recursive: true }); await mkdir(join(main, 'docs/history'));
  await writeFile(join(main, 'README.md'), '# Fixture\n');
  const pages: Record<string, [string, number, string]> = { 'docs/start.md': ['Start here', 1, 'start.'], 'docs/operate.md': ['Operate Graphyard', 1, 'operate.'], 'docs/build.md': ['Build integrations', 2, 'build.'], 'docs/contribute.md': ['Understand or contribute', 1, 'contribute.'], 'docs/history/audit.md': ['Understand or contribute', 2, 'audit.'], 'docs/protocol/roles.md': ['Agent protocol', 1, 'roles.'] };
  const page = (path: string, section: string, order: number, summary: string, body = 'Body.') => writeFile(join(main, path), `<!-- page: ${section} | ${order} | ${summary} -->\n# ${path}\n\n${body}\n`);
  for (const [path, [section, order, summary]] of Object.entries(pages)) await page(path, section, order, summary);
  execFileSync(process.execPath, ['scripts/check-docs.mjs', '--write'], { cwd: main });
  const agents = managedMasterInstructions(managedInstructions('# Fixture rules\n\nHand-written.\n', 'https://graphyard.example'));
  await writeFile(join(main, 'AGENTS.md'), agents);
  git(main, 'add', '.'); git(main, 'commit', '-q', '-m', 'base'); git(main, 'push', '-q', 'origin', 'main');
  execFileSync('git', ['clone', '-q', origin, branch], { stdio: 'ignore' }); git(branch, 'config', 'user.email', 't@example.com'); git(branch, 'config', 'user.name', 'T');
  git(branch, 'checkout', '-q', '-b', 'graphyard/gy-1-1');
  return { root, main, branch, git, page: (cwd: string, path: string, section: string, order: number, summary: string, body?: string) => writeFile(join(cwd, path), `<!-- page: ${section} | ${order} | ${summary} -->\n# ${path}\n\n${body ?? 'Body.'}\n`), agents };
}

async function fakeServer(work: () => Work[]) {
  const http = createServer((req, res) => {
    res.setHeader('Content-Type', 'application/json');
    if (req.url === '/api/status') return res.end(JSON.stringify({ actor: { id: 'worker-a', role: 'worker' }, baseBranch: 'main' }));
    if (req.url === '/api/work-snapshot') return res.end(JSON.stringify({ now: new Date().toISOString(), work: work() }));
    res.end(JSON.stringify(work()));
  });
  await new Promise<void>(resolve => http.listen(0, '127.0.0.1', resolve));
  const env: NodeJS.ProcessEnv = { ...process.env, GRAPHYARD_URL: `http://127.0.0.1:${(http.address() as any).port}`, GRAPHYARD_TOKEN: 'test-only' };
  for (const name of ['GRAPHYARD_TOKEN_FILE', 'GRAPHYARD_REQUEST_ID', 'HERDR_ENV', 'GRAPHYARD_HERDR_AGENT_KIND', 'GRAPHYARD_GENERATED_FILES']) delete env[name];
  return { env, close: () => new Promise<void>(resolve => http.close(() => resolve())) };
}
const sync = (cwd: string, env: NodeJS.ProcessEnv) => exec(process.execPath, [launcher, 'sync', 'GY-1'], { cwd, env }).then(result => ({ code: 0, output: JSON.parse(result.stdout) }), (error: any) => ({ code: error.code as number, output: JSON.parse(error.stdout) }));

test('integration:generated-index-no-conflict — two branches that each add a page merge without anyone hand-resolving the docs index: sync regenerates it, commits the merge, and the guard passes', async () => {
  const { root, main, branch, git, page } = await fixtureRepository();
  const item = { id: 'w1', key: 'GY-1', stage: 'build', ready: true, plannedFiles: ['docs/quickstart.md'], dependencies: [], workspaces: [{ epoch: 1, host: 'h', path: branch, branch: 'graphyard/gy-1-1' }], observation: null, submission: null } as unknown as Work;
  const shipped = { id: 'w9', key: 'GY-9', stage: 'done', plannedFiles: ['docs/glossary.md'], workspaces: [], delivery: { mergeSha: '', mergedAt: '' } } as unknown as Work;
  const server = await fakeServer(() => [item, shipped]);
  try {
    // Both sides add a page to the same numbered section, so the generated index conflicts textually.
    await page(branch, 'docs/quickstart.md', 'Start here', 2, 'quickstart.');
    execFileSync(process.execPath, ['scripts/check-docs.mjs', '--write'], { cwd: branch });
    git(branch, 'add', '.'); git(branch, 'commit', '-q', '-m', 'add quickstart');
    await page(main, 'docs/glossary.md', 'Start here', 2, 'glossary.');
    execFileSync(process.execPath, ['scripts/check-docs.mjs', '--write'], { cwd: main });
    git(main, 'add', '.'); git(main, 'commit', '-q', '-m', 'add glossary'); git(main, 'push', '-q', 'origin', 'main');
    (shipped as any).delivery.mergeSha = git(main, 'rev-parse', 'HEAD');
    git(branch, 'fetch', '-q', 'origin');
    assert.throws(() => git(branch, 'merge-tree', '--write-tree', '--name-only', '--no-messages', 'HEAD', 'origin/main'), (error: any) => /docs\/README\.md/.test(error.stdout), 'git itself reports the index conflict');
    const result = await sync(branch, server.env);
    assert.equal(result.code, 0, JSON.stringify(result.output));
    assert.equal(result.output.merged, true); assert.equal(result.output.ok, true);
    assert.deepEqual(result.output.regenerated, ['docs/README.md']);
    assert.deepEqual(result.output.generated, ['docs/protocol.md', 'docs/README.md']);
    assert.deepEqual(result.output.files.map((entry: any) => [entry.path, entry.kind]), [['docs/README.md', 'generated'], ['docs/quickstart.md', 'in-scope']], 'the regenerated index is generated, not an out-of-scope rewrite');
    assert.equal(git(branch, 'status', '--porcelain'), '', 'the merge is committed');
    assert.equal(git(branch, 'rev-list', '--merges', '--count', 'HEAD'), '1');
    const index = await readFile(join(branch, 'docs/README.md'), 'utf8');
    assert.ok(!hasConflictMarkers(index)); assert.match(index, /1\. \[docs\/start\.md\]/); assert.match(index, /\[docs\/glossary\.md\]/); assert.match(index, /\[docs\/quickstart\.md\]/);
    await exec(process.execPath, ['scripts/check-docs.mjs'], { cwd: branch });
    // A second sync with nothing to merge changes nothing.
    const again = await sync(branch, server.env);
    assert.equal(again.code, 0); assert.deepEqual(again.output.regenerated, []); assert.equal(git(branch, 'rev-list', '--count', 'HEAD'), '4');
  } finally { await server.close(); await rm(root, { recursive: true, force: true }); }
});

test('integration:generated-index-no-conflict — sync regenerates the managed AGENTS.md blocks, names the shipped items behind every remaining conflict, and completes the merge once the worker resolves them', async () => {
  const { root, main, branch, git, page } = await fixtureRepository();
  const item = { id: 'w1', key: 'GY-1', stage: 'build', ready: true, plannedFiles: ['docs/start.md', 'AGENTS.md'], dependencies: [], workspaces: [{ epoch: 1, host: 'h', path: branch, branch: 'graphyard/gy-1-1' }], observation: null, submission: null } as unknown as Work;
  const shipped = { id: 'w9', key: 'GY-9', stage: 'done', plannedFiles: ['docs/'], workspaces: [], delivery: { mergeSha: '', mergedAt: '' } } as unknown as Work;
  const older = { id: 'w8', key: 'GY-8', stage: 'done', plannedFiles: ['docs/start.md'], workspaces: [], delivery: { mergeSha: 'f'.repeat(40), mergedAt: '' } } as unknown as Work;
  const server = await fakeServer(() => [item, shipped, older]);
  try {
    // The branch's AGENTS.md block was rendered by an older CLI; main's by a newer one; both
    // sides also edit the same line of docs/start.md, which nobody can regenerate.
    const rewrite = async (cwd: string, transform: (text: string) => string) => writeFile(join(cwd, 'AGENTS.md'), transform(await readFile(join(cwd, 'AGENTS.md'), 'utf8')));
    await rewrite(branch, text => text.replace('Renew ownership at least every 30 seconds', 'Renew ownership at least every 20 seconds'));
    await page(branch, 'docs/start.md', 'Start here', 1, 'start.', 'Branch body.');
    git(branch, 'add', '.'); git(branch, 'commit', '-q', '-m', 'branch edits');
    await rewrite(main, text => text.replace('Renew ownership at least every 30 seconds', 'Renew ownership at least every 45 seconds'));
    await page(main, 'docs/start.md', 'Start here', 1, 'start.', 'Main body.');
    git(main, 'add', '.'); git(main, 'commit', '-q', '-m', 'main edits'); git(main, 'push', '-q', 'origin', 'main');
    (shipped as any).delivery.mergeSha = git(main, 'rev-parse', 'HEAD');
    const first = await sync(branch, server.env);
    assert.equal(first.code, 1); assert.equal(first.output.merged, false);
    assert.deepEqual(first.output.conflicts, [{ path: 'docs/start.md', generated: false, shippedBy: ['GY-9'], landedSince: true }], 'the remaining conflict names the item that landed it, not every item that ever touched the path');
    assert.deepEqual(first.output.regenerated, ['AGENTS.md (managed blocks rendered from the cli templates)']);
    assert.match(first.output.next, /rerun sync GY-1/);
    const agents = await readFile(join(branch, 'AGENTS.md'), 'utf8');
    assert.ok(!hasConflictMarkers(agents)); assert.match(agents, /every 30 seconds/); assert.match(agents, /^# Fixture rules\n\nHand-written\./, 'the hand-written text around the blocks is kept');
    assert.equal(agents, managedMasterInstructions(managedInstructions(agents, 'https://graphyard.example')), 'the blocks are exactly what the templates render');
    assert.ok(hasConflictMarkers(await readFile(join(branch, 'docs/start.md'), 'utf8')), 'the worker still owns the real conflict');
    // The worker resolves the remaining conflict and reruns sync: it finishes the merge.
    await page(branch, 'docs/start.md', 'Start here', 1, 'start.', 'Resolved body.');
    git(branch, 'add', 'docs/start.md');
    const second = await sync(branch, server.env);
    assert.equal(second.code, 0, JSON.stringify(second.output)); assert.equal(second.output.merged, true); assert.equal(second.output.ok, true);
    assert.equal(git(branch, 'status', '--porcelain'), ''); assert.equal(git(branch, 'rev-list', '--merges', '--count', 'HEAD'), '1');
    assert.deepEqual(second.output.files.map((entry: any) => [entry.path, entry.kind]), [['AGENTS.md', 'in-scope'], ['docs/start.md', 'in-scope']]);
  } finally { await server.close(); await rm(root, { recursive: true, force: true }); }
});

test('integration:generated-index-no-conflict — the pure helpers behind sync: block regeneration refuses conflicts outside the blocks, and attribution falls back to every shipper', () => {
  const url = 'https://graphyard.example';
  const clean = managedInstructions('# Rules\n', url);
  const inside = clean.replace('Renew ownership at least every 30 seconds', '<<<<<<< HEAD\nRenew ownership at least every 20 seconds\n=======\nRenew ownership at least every 45 seconds\n>>>>>>> origin/main');
  assert.equal(regenerateManagedBlocks(inside, text => managedInstructions(text, url)), clean);
  const outside = `<<<<<<< HEAD\n# Rules\n=======\n# Other rules\n>>>>>>> origin/main\n${clean.slice('# Rules\n'.length)}`;
  assert.equal(regenerateManagedBlocks(outside, text => managedInstructions(text, url)), null, 'a conflict in the hand-written text is never resolved by the renderer');
  assert.equal(regenerateManagedBlocks(`${clean}${clean}`, text => managedInstructions(text, url)), null, 'duplicated markers are malformed, not resolved');
  assert.equal(managedServerUrl(clean), url); assert.equal(managedServerUrl('# nothing'), null);
  assert.ok(hasConflictMarkers('a\n=======\nb') && !hasConflictMarkers('a\n====\n<<<<<<<x'));
  const landed = (sha: string) => sha === 'l'.repeat(40);
  const all = [
    { id: 'a', key: 'GY-A', stage: 'done', plannedFiles: ['docs/'], delivery: { mergeSha: 'l'.repeat(40) } },
    { id: 'b', key: 'GY-B', stage: 'done', plannedFiles: ['src/x.ts'], observation: { files: ['src/x.ts'], mergeSha: 'o'.repeat(40) } },
    { id: 'c', key: 'GY-C', stage: 'review', plannedFiles: ['src/x.ts'] },
  ] as unknown as Work[];
  assert.deepEqual(attributeConflicts(['docs/a.md', 'src/x.ts', 'docs/README.md'], all, landed, ['docs/README.md']), [
    { path: 'docs/a.md', generated: false, shippedBy: ['GY-A'], landedSince: true },
    { path: 'src/x.ts', generated: false, shippedBy: ['GY-B'], landedSince: false },
    { path: 'docs/README.md', generated: true, shippedBy: ['GY-A'], landedSince: true },
  ]);
});

test('integration:generated-index-no-conflict — AGENTS.md carries exactly the blocks this tree\'s templates render, so drift is caught here rather than by a committed diff in every PR', async () => {
  const agents = await readFile(join(repositoryRoot, 'AGENTS.md'), 'utf8');
  const url = managedServerUrl(agents);
  assert.ok(url, 'AGENTS.md names the Graphyard server its coordination block was rendered for');
  assert.equal(managedInstructions(agents, url!), agents, 'the coordination block matches src/repository-setup.ts; run graphyard init --apply (or update the template) and commit');
  assert.equal(managedMasterInstructions(agents), agents, 'the master block matches src/master.ts; run graphyard master init and commit');
});

test('manual:overlap-docs — the guides describe optimistic dispatch, smallest-scope-first dispatch, conflict sets, generated files and sync regeneration', async () => {
  const read = (path: string) => readFile(join(repositoryRoot, path), 'utf8');
  const coordination = await read('docs/coordination.md'), master = await readMasterGuide(), development = await read('docs/development.md');
  for (const fragment of ['optimistic', 'smallest', 'highConflict', 'GRAPHYARD_GENERATED_FILES', 'generated', 'merge-tree', 'regenerate']) assert.ok(coordination.includes(fragment), `docs/coordination.md must mention ${fragment}`);
  for (const fragment of ['optimistic', 'smallest', 'merge-tree', 'conflicts', 'overlap']) assert.ok(master.includes(fragment), `docs/master-agent.md must mention ${fragment}`);
  for (const fragment of ['generated in full', 'docs:check', 'GRAPHYARD_GENERATED_FILES', 'AGENTS.md']) assert.ok(development.includes(fragment), `docs/development.md must mention ${fragment}`);
  const help = execFileSync(process.execPath, [launcher, 'help'], { encoding: 'utf8', env: { ...process.env, GRAPHYARD_URL: 'http://127.0.0.1:9', GRAPHYARD_TOKEN: 'x' } });
  assert.match(help, /master dispatch GY-N PROFILE +Invite a worker/); assert.doesNotMatch(help, /--allow-overlap/); assert.match(help, /sync GY-N[^\n]*regenerate generated files/);
});
