import { registryHelp } from './master-registry.js';

/** `graphyard help` for the master subcommands, in the order the guide introduces them. */
export const masterHelp = [
  '  master init --token-stdin [--herdr-workspace ID] [--browser-profile PROFILE]',
  '              [--dispatch-interval SECONDS] [--reviewer-profile NAME] [--producer-timeout MINUTES]',
  '                                Install the recommended master-agent operating mode; PROFILE is',
  "                                the operator's Chrome profile the master administers GitHub",
  '  master start AGENT_KIND       Launch the dedicated visible Herdr master session',
  '  master worker add FILE        Add an existing or launchable Herdr worker profile',
  '  master reviewer setup [--name NAME]     Register the separate reviewer GitHub App; NAME',
  "                                defaults to reviewer, within GitHub's 34-character limit",
  '  master reviewer bind FILE --key-stdin   Bind an existing reviewer App (IDs in FILE, PEM on stdin)',
  '  master reviewer add FILE | remove NAME   Add or remove a reviewer launch profile',
  '  master producer add FILE | replace FILE | remove NAME  Manage proof-producer profiles',
  '  master review GY-N [PROFILE]  Launch the bound reviewer on the exact current candidate;',
  '                                master run does this on its own for every submitted head',
  '  master protection [--apply]   Reconcile branch protection with every open review policy',
  '  master browser FLOW [--dry-run]',
  "                                Perform GitHub administration through the operator's browser",
  '                                profile: app-permissions, installation-accept, or protection;',
  '                                recorded, API-verified, audited',
  '  master harness [KIND] [--apply]  Generate the master\'s own harness permissions',
  '  master status                 Graphyard work truth joined with Herdr session health, the',
  '                                dispatch order, overlaps and merge conflicts',
  '  master dispatch GY-N PROFILE [--allow-overlap]',
  '                                Invite a worker to claim ready work in a visible tab; an',
  '                                item whose planned files overlap a claimed or unmerged item',
  '                                is held unless --allow-overlap is passed',
  '  master settle-containment GY-N REASON',
  '                                Settle a containment quarantine whose supervisor this host',
  '                                verifies dead; unverifiable signals refuse',
  '  master merge GY-N|--all       Merge exact authorized candidates without bypasses',
  '  master config FIELD=VALUE…   Tune owned run settings and profile accounts',
  '                                (accounts:PROFILE=a,b); autoMerge and credential paths stay operator-only',
  '  master verify-deployment GY-N Verify that the deployed release serves a delivery and',
  '                                emits the current instructions; refuse stale or local-only',
  '                                observations, record the exact release observed',
  '  master run [--once] [--interval SECONDS]',
  '                                Run the durable coordination loop as a supervised process; it',
  '                                launches the reviewer and proof producers for every submitted',
  '                                head within 30 seconds of the request, and decides every open',
  '                                worker scope request on the cycle it appears',
  '  master autonomy [--admin-token-stdin --apply]  Provision the master and approver identities',
  '  master create FILE|release GY-N|unblock GY-N|requirements GY-N FILE REASON  Own intent',
  '  master scope GY-N [REASON]    Approve a worker scope request the loop refused: add its',
  '                                requested paths to plannedFiles while the attempt keeps its',
  '                                lease. master run decides every request the item itself',
  '                                already implies, so this is the override for the rest',
  '  master decide GY-N ACTION [JSON|@FILE] REASON  Request a two-party decision',
  '  master withdraw GY-N DECISION REASON  Take back the master\'s own requested decision',
  '  master decisions GY-N | approver GY-N DECISION [KIND] | approve GY-N DECISION REASON',
  '  master principals [--apply]   Preview or apply a roster rotation keeping live principals',
  '  master restart                Restart this host\'s master loop detached',
  '  master environments [--create KIND,…] [--apply]  Agent accounts, quota, profiles',
  '  master guide                  Print the complete master-agent operating guide',
  ...registryHelp,
];
