// Verifies every relative link and anchor under README.md and docs/, and keeps the generated
// index pages current. An index page is generated in full — nothing in it is hand-written — so
// two concurrent pull requests never hand-merge it: `node scripts/check-docs.mjs` fails when a
// generated page is stale or missing, `--write` regenerates them, and `--manifest` prints their
// paths so `graphyard sync` regenerates them on a merge conflict and the control plane's
// regression guard (`GRAPHYARD_GENERATED_FILES`) treats them as generated rather than owned.
//
// A page declares where it is listed with one line near its top:
//   <!-- page: Section | order | summary -->
// Each generated index lists every such page in its directories (non-recursive), grouped by the
// sections in the order given. The first section is a numbered path; the others are bulleted.
// The prose above an index lives here, in `head`, and below it in `tail`.
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';

const write = process.argv.includes('--write');

// Generation order matters: docs/README.md lists docs/protocol.md by its page line.
const generatedIndexes = [
  {
    file: 'docs/protocol.md',
    directories: ['docs/protocol'],
    sections: ['Agent protocol'],
    head: `<!-- page: Build integrations | 1 | roles, requests, work commands, leases, workspaces, evidence, and the webhook, one topic per page. -->
# Agent protocol and HTTP API

All control-plane endpoints except \`/healthz\` require \`Authorization: Bearer TOKEN\`. Use HTTPS for remote machines. API credentials are not Git credentials.

One topic per page. This index is generated in full; never edit it by hand.`,
    tail: '',
  },
  {
    file: 'docs/README.md',
    directories: ['docs', 'docs/history'],
    sections: ['Start here', 'Operate Graphyard', 'Build integrations', 'Understand or contribute', 'Maintainer and historical records'],
    head: `# Graphyard documentation

Choose one path; the reference guides are there when a gate or integration needs deeper investigation. This index is generated in full; never edit it by hand.`,
    tail: 'Historical records explain past decisions, not current setup.',
  },
];
const generatedMarker = '<!-- generated by scripts/check-docs.mjs; do not edit: run npm run docs:check -- --write -->';

if (process.argv.includes('--manifest')) {
  console.log(JSON.stringify({ generated: generatedIndexes.map(index => index.file), regenerate: 'node scripts/check-docs.mjs --write' }));
  process.exit(0);
}

function markdownFiles(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const target = join(directory, entry.name);
    return entry.isDirectory() ? markdownFiles(target) : entry.name.endsWith('.md') ? [target] : [];
  });
}

function headingSlugs(file) {
  const counts = new Map();
  return [...readFileSync(file, 'utf8').matchAll(/^#{1,6}\s+(.+)$/gm)].map(match => {
    let slug = match[1]
      .toLowerCase()
      .replace(/<[^>]+>/g, '')
      .replace(/[`*_~]/g, '')
      .replace(/[^\p{L}\p{N}\s-]/gu, '')
      .trim()
      .replace(/\s+/g, '-');
    const duplicate = counts.get(slug) ?? 0;
    counts.set(slug, duplicate + 1);
    if (duplicate) slug += `-${duplicate}`;
    return slug;
  });
}

const headings = new Map();
const failures = [];

// ---- Generated indexes -------------------------------------------------------------------

const pageLine = /^<!--\s*page:\s*([^|]+?)\s*\|\s*(\d+)\s*\|\s*(.+?)\s*-->\s*$/m;
const generatedFiles = new Set(generatedIndexes.map(index => index.file));

function pageEntry(file, content = readFileSync(file, 'utf8')) {
  const meta = content.slice(0, 500).match(pageLine);
  if (!meta) return null;
  const title = content.match(/^#\s+(.+)$/m)?.[1];
  if (!title) failures.push(`${file}: an indexed page needs a level-one heading`);
  return { file, section: meta[1], order: Number(meta[2]), summary: meta[3], title: title ?? file };
}

function renderIndex({ file: indexFile, directories, sections, head, tail }) {
  const pages = directories.flatMap(directory => readdirSync(directory, { withFileTypes: true })
    .filter(entry => entry.isFile() && entry.name.endsWith('.md'))
    .map(entry => join(directory, entry.name)))
    .filter(file => file !== indexFile)
    // Another generated index is listed by the page line its own head declares, so a stale or
    // missing copy on disk never changes what this index says about it.
    .map(file => generatedFiles.has(file) ? pageEntry(file, render(generatedIndexes.find(index => index.file === file))) : pageEntry(file)).filter(Boolean);
  for (const page of pages) if (!sections.includes(page.section)) failures.push(`${page.file}: section "${page.section}" is not listed by the index in ${indexFile}`);
  const listed = new Set(pages.map(page => page.file));
  for (const directory of directories) for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const file = join(directory, entry.name);
    if (!entry.isFile() || !entry.name.endsWith('.md') || file === indexFile || listed.has(file) || generatedFiles.has(file)) continue;
    failures.push(`${file}: add a <!-- page: Section | order | summary --> line so ${indexFile} lists it`);
  }
  const body = sections.map((section, position) => {
    const entries = pages.filter(page => page.section === section).sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));
    if (!entries.length) failures.push(`${indexFile}: section "${section}" lists no pages`);
    const lines = entries.map((page, index) => `${position === 0 ? `${index + 1}.` : '-'} [${page.title}](${relative(dirname(indexFile), page.file)}) — ${page.summary}`);
    return `## ${section}\n\n${lines.join('\n')}\n`;
  }).join('\n');
  return `${head.trim()}\n\n${body}${tail ? `\n${tail.trim()}\n` : ''}`;
}

// The marker sits after a leading page line so the page stays listed by the index above it.
function render(index) {
  const content = renderIndex(index);
  const [first, ...rest] = content.split('\n');
  return pageLine.test(first) ? [first, generatedMarker, ...rest].join('\n') : `${generatedMarker}\n${content}`;
}

for (const index of generatedIndexes) {
  const generated = render(index);
  const current = existsSync(index.file) ? readFileSync(index.file, 'utf8') : null;
  if (current === generated) continue;
  if (!write) { failures.push(`${index.file}: the generated index is ${current === null ? 'missing' : 'stale'}; run npm run docs:check -- --write`); continue; }
  writeFileSync(index.file, generated);
  console.log(`Regenerated ${index.file}`);
}

// ---- Links and anchors -------------------------------------------------------------------

const files = ['README.md', ...markdownFiles('docs')];
for (const file of files) {
  const content = readFileSync(file, 'utf8');
  for (const match of content.matchAll(/!?\[[^\]]*\]\(([^)]+)\)/g)) {
    const link = match[1];
    if (/^(https?:|mailto:)/.test(link)) continue;
    const hash = link.indexOf('#');
    const target = hash < 0 ? link : link.slice(0, hash);
    const anchor = hash < 0 ? '' : link.slice(hash + 1).toLowerCase();
    const destination = target.startsWith('/docs/')
      ? resolve(`${target.slice(1)}${target.endsWith('.md') ? '' : '.md'}`)
      : resolve(dirname(file), target || file.split('/').at(-1));
    try {
      if (!statSync(destination).isFile()) throw new Error('not a file');
    } catch {
      failures.push(`${file}: missing ${link}`);
      continue;
    }
    if (anchor) {
      if (!headings.has(destination)) headings.set(destination, headingSlugs(destination));
      if (!headings.get(destination).includes(anchor)) failures.push(`${file}: missing anchor ${link}`);
    }
  }
}

if (failures.length) {
  console.error([...new Set(failures)].join("\n"));
  process.exit(1);
}

console.log(`Checked ${files.length} Markdown files; all relative links, anchors and generated indexes resolve.`);
