// The master coordinator: profiles and config, agent launches, dispatch, status, the guarded merge
// and autonomy. Its modules live under src/master/, one concern each (GY-177); this path re-exports
// every public name so existing imports keep working.
export { childRunner, defaultChildRun, type ChildRun, type ChildRunOptions } from './child-runner.js';
export { assertSessionName, distinctSessionName, nameForLaunch, sessionName, sessionNameDigestLength, sessionNameDistinguisher, sessionNameDistinguisherLimit, sessionNameLimit, sessionNameRefusal, SessionNameRefusedError, sessionNameRule, suffixedSessionName } from './session-name.js';
export { requestPlaceholder } from './harness.js';
export { agentKindSchema, environmentKinds, environmentVariable, agentEnvironmentSchema, workerProfileSchema, reviewerProfileSchema, producerProfileSchema, profileConcurrency, sessionAgentName, isProfileSession, profileSessions, profileAtLimit, reviewerIdentitySchema, masterRunSchema, masterBrowserSchema, agentIdentitySchema, masterConfigSchema, mergeBatchSize, assertMasterBinding, type EnvironmentKind, type AgentEnvironment, type WorkerProfile, type ReviewerProfile, type ProducerProfile, type ReviewerIdentity, type MasterRun, type MasterBrowser, type MasterConfig } from './master/profiles.js';
export { managedMasterInstructions } from './master/instructions.js';
export { privateFile, readCredentialFile, assertOutsideWorktrees, externalCredential, loadMasterConfig, readWorkerCredential, inspectWorkerCredentials, readProducerCredential, inspectProducerCredentials, atomicPrivateWrite, setupMaster, saveWorkerProfile, saveProducerProfile, masterOwnedRunFields, masterSettingsFromArgs, saveMasterSettings, replaceProducerProfile, removeProducerProfile, producerCommand, masterBoundSettings, masterConfigChanges, liveMasterConfig, type MasterOwnedSettings, type ConfigReload, type LiveMasterConfig } from './master/config.js';
export { agentEnvironmentRoot, discoverAgentEnvironments, createAgentEnvironment, prepareAgentEnvironment, loginCommand, defaultQuotaCeilingPercent, checkAgentEnvironment, NoHealthyAccountError, unknownResetHoldMs, profileAccount, runtimeLogin, ownLoginAccounts, ownLoginHold, selectionKey, environmentLogPath, readEnvironmentLog, recordObservedExhaustion, observedExhaustions, describeObservedExhaustion, recordEnvironmentLog, selectAccount, onSelectedSession, heldAwareProbe, withHeldAccounts, openCodeAllowAll, agentLaunchPlan, accountLaunch, sharedGitDirectory, inspectProfileAccounts, roleCapacity, setupAgentEnvironments, type AccountUsage, type EnvironmentHealth, type EnvironmentProbe, type LaunchRole, type AccountSkipCause, type AccountSkip, type ObservedExhaustion, type AccountSelection, type EnvironmentLog, type LaunchAccount, type LaunchSelection, type ProfileAccountHealth, type RoleCapacity } from './master/environments.js';
export { preservePartialWork, launchRequestContracts, launchRoleContracts, launchDelivery, requestContractRefusal, launchCommandLimit, launchDirectory, shellWord, launchVariable, writeLaunchFiles, launchCommand, agentStartTimeoutMs, agentStartCeilingMs, startPollMs, paneLineLimit, startedStates, promptableStates, runtimeScreens, SessionStartError, consentAnswerAttempts, consentSettleMs, readPaneScreen, paneLastLine, commandEchoing, observeStart, awaitRuntimeStart, startAgentSession, promptAttempts, promptAcceptMs, promptRetryPauseMs, PromptNotAcceptedError, herdrErrorCode, herdrErrorText, nameRefusedByRuntime, deliverPrompt, defaultAcknowledgementSeconds, sustainedActivityMs, acknowledgementMs, sessionActivity, activeStates, screenDigest, readSessionScreen, sessionWords, acknowledgeLaunch, markReprompted, settlementDue, neverStartedReason, settlementReason, neverStarted, repromptText, type RequestDelivery, type LaunchFiles, type StartState, type StartObservation, type StartBounds, type SessionStart, type PromptDelivery, type LaunchAcknowledgement, type SessionActivity, type ScreenReader } from './master/launch.js';
export { runtimePromptTextLimit, destructivePrompt, classifyRuntimePrompt, continueAfterDecline, type RuntimePrompt } from './master/runtime-prompt.js';
export { herdrWorkspaceHealth, agentRuntimeTimeoutMs, agentRuntimeRun, herdrJson, listHerdrAgents, observeHerdrAgents, closeHerdrPane, createdHerdrTab, stopCreatedHerdrTab, type HerdrAgent } from './master/herdr.js';
export { containmentPhase, containmentHold, containmentQuarantines, snapshotWithClock, verifyContainmentDeath, assessContainment, type ContainmentAssessment, type ContainmentPhase } from './master/containment.js';
export { agentOwner, humanOwner, installationOwner, installationSources, workAttentionOwner, workAttentionCauses, controlPlaneAttention, fleetStatus, productionSummary, type ControlPlaneStatus, type AttentionOwner, type AttentionItem, type WorkAttentionCause } from './master/attention.js';
export { dependencyDirectories, defaultReclaimIdleHours, defaultDiskThresholdGb, reclaimIdleMs, diskThresholdBytes, lockfiles, worktreesDirectory, diskExhaustion, reclaimAdvice, exhaustedPath, diskExhaustionMessage, writeFailure, freeBytes, worktreeActivity, inventoryWorktrees, planWorktreeReclaim, reclaimWorktrees, defaultWorktreeRemovalLimit, worktreeInventoryFile, worktreeReclaimAuditFile, readWorktreeInventoryCache, writeWorktreeInventoryCache, statusWorktreeInventory, worktreeRemovalReason, removeReclaimableWorktrees, diskPressure, diskPressureAttention, worktreeRootAttention, allocateManagedCheckout, settleCheckout, managedRootStatus, sharedInstallMarker, shareDependencies, sharedInstallSource, type WorktreeDependency, type WorktreeEntry, type ReclaimDisposition, type WorktreeReclaimCandidate, type WorktreeReclaimReport, type HeldWorktree, type WorktreeInventoryCache, type WorktreeRemoval, type WorktreeRemovalReport, type DiskPressure, type SharedDependency, type SharedDependencies } from './master/worktrees.js';
export { mergeProtocolSkew, describeDispatch, roleConcurrency, concurrencyStarvedMs, concurrencyAttention, buildMasterStatus, mergeStep, branchReport, dispatchSchedule, sequenceAdvice, recoveredDeliveries, mergeToProductionMs, latencyPercentiles, type SessionRetryReport, type DispatchSessions, type RoleConcurrencyProfile, type RoleConcurrencyReport, type RoleProfiles } from './master/status.js';
export { sessionHarnessPlan, sessionHarnessFile, prepareSessionHarness, startMaster, humanOnlyDecisions, masterOperatorCapabilities, approverAgentCapabilities, autonomyPlan, masterHarness, emptySourceStarts, workerHarnessPlan, branchRestoration, blockerCommands, unrunnableRemedies, installWorkerHarness, type SessionRole, type SessionHarnessInput, type UnrunnableRemedy } from './master/harness.js';
export { assertClaimDeadline, describeOverlap, assertDispatchable, dispatchWork, herdrAttach, consentHold, autonomousSession, destructivePromptGuidance, workerPrompt, workerLaunchTimeoutMs, releaseWorkerLaunch, prepareWorkerLaunch, type DispatchOptions } from './master/dispatch.js';
export { dispatchReservationMs, dispatchReservationDirectory, DispatchReservedError, dispatchReserved, watchSupervisorRunning } from './master/dispatch-reservation.js';
export { daemonExecutor, unauthorizedMergeViolation, mergedWithoutAuthorization, assertMergeCandidate, currentMergeCandidates, continueMergeBatch, assertMergeProtection, readBaseTip, assertQueuedLanding, repostCarriedApproval, mergeBinding, transientMergeRace, mergeWork, mergeExecutor, type MergeExecutor, type MergeOutcome, type CarriedApprovalRepost } from './master/merge.js';
export { setupAutonomy, agentToken, decisionInput, approvedMerge, approvedMerges, previewPrincipalRotation, readProposedRoster, restartMasterLoop, approverDistinguisher, approverSessionName, approverProfile, escalationProfile, approverRuntime, approverProfiles, type ApproverSelection, selectApproverAccount, heldRuntimeLogin, approverSessionId, launchApprover, approverLaunchSchema, type ApproverLaunch, readApproverLaunch, saveApproverLaunch, approverRoleHealth, escalationRoleHealth, escalationSessionSchema, type EscalationSession, retainedEscalationSessions, escalationSessionMs, readEscalationSessions, saveEscalationSession, registeredReview, type SessionRegistrar, verifiedContext, launchEscalationHandler, broadScopeFlag, guardBroadScope, autonomySubcommands, runAutonomyCommand, type AutonomyDependencies } from './master/autonomy.js';
