// The durable coordination loop. Every step is a pure decision over one Graphyard snapshot plus
// an injected effect, so the same cycle runs under systemd, under Herdr, or inside a test with no
// process supervision at all. The daemon is a coordinator: it never claims a lease, never produces
// evidence, never calls an operator route, and reaches GitHub only through the guarded merge.
//
// Its modules live under src/daemon/, one concern each (GY-177); this path re-exports every public
// name so existing imports keep working.
export { threadResolutionGraceMs, threadsAwaitReview } from './merge-queue.js';
export { daemonActionKinds, daemonActionFaultKind, storeAction, faultActionKey, actionDetailMax, daemonActionSchema, cycleStepNames, cycleStepsSchema, emptyCycleSteps, cycleMetricsSchema, containmentRetentionSchema, retainedContainments, deploymentObservationSchema, reclaimSummarySchema, scopeMeasurementSchema, itemClockSchema, latencySampleSchema, silenceSchema, orphanObservationSchema, approvalWatchSchema, carriedSession, cycleFailureSchema, daemonStateSchema, retainedActions, retainedMetrics, profileCooldownMs, maxProofAttempts, retainedScopeDecisions, retainedSamples, retainedClocks, reclaimIntervalMs, emptyDaemonState, daemonStatePath, readDaemonState, writeDaemonState, pruneDaemonState, boundDaemonState, boundDeployment, acquireDaemonLock, type DaemonActionKind, type DaemonAction, type CycleStepName, type StepCost, type CycleSteps, type CycleMetrics, type ContainmentRetention, type DeploymentObservation, type ReclaimSummary, type ScopeMeasurement, type ItemClock, type LatencySample, type OrphanObservation, type ApprovalWatch, type CycleFailures, type DaemonState } from './daemon/state.js';
export { reconcilePendingActions, dispatchKey, candidateKey, closeKey, decisionKey, scopeKey, scopeAnsweredAt, scopeOutcomeAnswered, answeringWidening } from './daemon/reconcile.js';
export { percentiles, scopeBudget, stageMetrics, missingProofs, silenceBudgetMs, actionableSubjects, trackSilence, silenceReport, latencyTargets, observeItemClock, latencyBudget, type ActionableSubject, type SilenceEntry, type SilenceReport, type LatencyBudget } from './daemon/metrics.js';
export { orphanedSupervisors, stopWatchSupervisor, profileHealth, readyToRetry, recordProfileFailure, clearProfileFailure, type OrphanSupervisor, type ProfileHealth } from './daemon/sessions.js';
export { standingVerdict, reworkObservationMaxAgeMs, githubPause, observedFrom, reworkObservationWait, routineDecisionActions, scopeRoutineDecision, routineDecision, supersededLeaseLoss, resolveCovers, decisionReasonMax, setAsideFollowUpThreads, threadReworkSummary, proofRework, failedCheckRework, syncConflict, botThreadReworkRounds, reworkThreads, fitDecisionReason, boundDetail, detailChanged, namePaths, reworkGroundsMin, reworkDecisionReason, maxRefusalAnswers, refusalNamedIn, workerStopped, withheldDecision, approverJudgeBoundMs, approverSettleMs, maxApproverLaunches, maxApproverCloses, maxDecisionRequests, approvalStep, mergeableCandidate, type StandingVerdict, type GitHubPause, type RoutineDecisionAction, type RoutineDecision, type ApprovalStep } from './daemon/decisions.js';
export { cycleCost, loopLiveness, cycleFailureAttentionAfter, cycleFailureCeilingMs, cycleFailureDelay, cycleFailureStart, cycleFailureCeiling, describeFailingCall, noteCycleFailure, noteCycleSuccess, noteUnhandled, namedEffects, boundedPersist, loopAttention, watchdogPlan, actionableIntervalMs, cycleDelay, type LoopState, type LoopLiveness, type CycleCost } from './daemon/liveness.js';
export { stoppedStates, failoverKey, capacityKey, preserveKey, findingRecheckMs, launchAppearanceMs, handlerSettleMs, blockedPromptFailMs, blockedPromptAnswers, blockedPromptSettleMs, promptDigest, snapshotRetryDelayMs, retriedSnapshot, relaunchSession, daemonEffects, type LaunchedSession, type DaemonEffects } from './daemon/effects.js';
export { runCycle } from './daemon/cycle.js';
export { diagnosisStep, diagnosisSubjects, diagnosisInput, diagnosisPrompt, diagnosisReport, diagnosesSettled, clearDiagnoses, fixItem, namedPullRequests, isInvariantKind, diagnosticianRole, standingFaultClassItem, answeringItem, type DiagnosticianEffects, type DiagnosisSubject, type DiagnosisContext } from './daemon/diagnosis.js';
export { cycleFaults, timingFaultAttention, onceAnnotations, herdrFaultKinds, restatements, endFailingRuns, fileRecurringFaultClasses, faultRecurrenceReport, faultStep, type ReportedAttention, type FaultSources } from './daemon/faults.js';
export { automaticScopeGrounds, successorStep } from './daemon/cycle-scope.js';
export { closeEndedWorkerPanes } from './daemon/cycle-reclaim.js';
export { mergeRaceRetries, waitingInMergeQueue, mergeRetryBaseMs, mergeRetryCapMs, mergeRetryDue } from './daemon/cycle-delivery.js';
export { deploymentPageSize, deploymentListingPages, maxDeploymentRequests, productionEnvironmentRecord, observeDeployment } from './daemon/deployment.js';
export { daemonSummary, noteConfigReload, noteWatchdog, runDaemon } from './daemon/run.js';
