import { z } from 'zod';
import { activeLease, demand, type Principal, type ScopeFile, type Work } from './model.js';
import type { Store } from './store.js';
import { classifyScope, inPlannedScope, shippedBy, type ScopeFinding } from './regression-guard.js';

/**
 * Local half of the regression guard, for `graphyard sync`. Parses `git diff --raw -M -z
 * --no-abbrev BASE HEAD` and `git diff --numstat -M -z BASE HEAD`, both taken directly against
 * the fetched base tip, into the same file records the control plane derives from the provider.
 * Every record here already differs from the base tip; the classifier decides which are allowed.
 */
const statuses: Record<string, ScopeFile['status']> = { A: 'added', D: 'removed', M: 'modified', R: 'renamed', C: 'copied', T: 'changed' };
const zero = /^0+$/;
export function parseLocalScopeDiff(raw: string, numstat: string): ScopeFile[] {
  const counts = new Map<string, { additions: number; deletions: number; binary: boolean }>();
  const numstatTokens = numstat.split('\0');
  for (let i = 0; i < numstatTokens.length; i++) {
    const match = numstatTokens[i].match(/^(\d+|-)\t(\d+|-)\t(.*)$/s);
    if (!match) continue;
    const binary = match[1] === '-';
    // A rename carries an empty path followed by the old and new paths as separate tokens.
    const path = match[3] !== '' ? match[3] : numstatTokens[(i += 2)];
    counts.set(path, { additions: binary ? 0 : Number(match[1]), deletions: binary ? 0 : Number(match[2]), binary });
  }
  const files: ScopeFile[] = [];
  const tokens = raw.split('\0');
  for (let i = 0; i < tokens.length; i++) {
    const header = tokens[i].match(/^:(\d+) (\d+) ([0-9a-f]+) ([0-9a-f]+) ([A-Z])\d*$/);
    if (!header) continue;
    const [, , , oldSha, newSha, code] = header;
    const status = statuses[code] ?? 'modified';
    const moved = code === 'R' || code === 'C';
    const previousPath = moved ? tokens[++i] : undefined;
    const path = tokens[++i];
    const count = counts.get(path) ?? { additions: 0, deletions: 0, binary: false };
    const file: ScopeFile = { path, status, sha: zero.test(newSha) ? null : newSha, additions: count.additions, deletions: count.deletions, binary: count.binary,
      // The diff is against the base tip itself: the old side is exactly what the base holds.
      baseSha: moved ? null : zero.test(oldSha) ? null : oldSha };
    if (previousPath) { file.previousPath = previousPath; file.previousBaseSha = zero.test(oldSha) ? null : oldSha; }
    files.push(file);
  }
  return files;
}

export function localScopeFindings(plannedFiles: string[], raw: string, numstat: string, generated: readonly string[] = []): ScopeFinding[] {
  return classifyScope(plannedFiles, parseLocalScopeDiff(raw, numstat), generated);
}

/**
 * Generated files a repository declares for `graphyard sync`: the manifest `scripts/check-docs.mjs
 * --manifest` prints — the exact paths its `--write` renders in full. A repository without the
 * script declares none, and sync regenerates nothing.
 */
export interface GeneratedManifest { files: string[]; regenerate: string[] }
export function parseGeneratedManifest(output: string): GeneratedManifest | null {
  try {
    const parsed = JSON.parse(output);
    const files = Array.isArray(parsed?.generated) ? parsed.generated.filter((entry: unknown): entry is string => typeof entry === 'string' && !!entry) : [];
    const regenerate = typeof parsed?.regenerate === 'string' ? parsed.regenerate.split(/\s+/).filter(Boolean) : [];
    return files.length && regenerate.length ? { files, regenerate } : null;
  } catch { return null; }
}

/** Lines git leaves in a file it could not merge. */
export const hasConflictMarkers = (text: string) => /^(<{7}|={7}|>{7}|\|{7})( |$)/m.test(text);

/**
 * The managed `AGENTS.md` blocks are generated by `graphyard init` and `master init`, so a merge
 * conflict inside them is resolved by rendering the blocks afresh around the hand-written text.
 * A conflict that reaches outside the blocks — or one that duplicates the block markers, which
 * the renderers refuse as malformed — is left for the worker; nothing is guessed.
 */
export function regenerateManagedBlocks(conflicted: string, render: (text: string) => string): string | null {
  try {
    const rendered = render(conflicted);
    return hasConflictMarkers(rendered) ? null : rendered;
  } catch { return null; }
}
export const managedServerUrl = (text: string) => text.match(/uses Graphyard at (\S+) for ownership/)?.[1] ?? null;

/**
 * Which shipped work each remaining conflict comes from: the delivered items whose merge commit
 * the sync brings in and whose planned scope or observed diff covers the path. When none of the
 * newly landed items covers it, every delivered item that ever shipped the path is named instead.
 */
export function attributeConflicts(paths: string[], all: Work[], landed: (sha: string) => boolean, generated: readonly string[] = []) {
  const arrived = all.filter(item => item.stage === 'done' && [item.delivery?.mergeSha, item.observation?.mergeSha].some(sha => !!sha && landed(sha)));
  return paths.map(path => {
    const covers = (item: Work) => inPlannedScope(item.plannedFiles ?? [], path) || (item.observation?.files ?? []).includes(path);
    const causes = arrived.filter(covers).map(item => item.key);
    return { path, generated: generated.includes(path), shippedBy: causes.length ? causes : shippedBy(path, all), landedSince: causes.length > 0 };
  });
}

/**
 * A base sync that carries the base branch's own workflow changes (GY-1098). A worker's push
 * credential carries `workerPushPermissions`; when GitHub still refuses a push whose commits change
 * `.github/workflows` (an installation that has not granted Workflows) — including the merge of a
 * base that changed them — the worker names the merge commit instead and the control plane pushes it
 * with its own App, which holds `workflows: write`, only when the commit is a pure base sync:
 * a merge whose first parent is the assigned branch's head on GitHub (a fast-forward), whose
 * second parent is in origin/BASE, and whose workflow files are byte-identical to that parent
 * except for paths in plannedFiles. The control plane rebuilds the commit from the base tree plus
 * the listed entries through GitHub's Git Data API and refuses unless the rebuilt tree and commit
 * are the named ones, so an entry list that hides a workflow change cannot produce the commit; entries
 * must be file-level paths, and one at `.github/workflows` or an ancestor of it is a workflow change.
 */
export const workflowsDirectory = '.github/workflows/';
const sha40 = z.string().regex(/^[a-f0-9]{40}$/);
const person = z.object({ name: z.string(), email: z.string(), date: z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}$/) }).strict();
export const syncPushRequest = z.object({
  epoch: z.number().int().positive(), commit: sha40, tree: sha40, parents: z.array(sha40).min(1).max(8),
  message: z.string(), author: person, committer: person, signature: z.string().optional(),
  entries: z.array(z.object({ path: z.string().min(1), mode: z.enum(['100644', '100755', '120000', '160000']), type: z.enum(['blob', 'commit']), sha: sha40.nullable() }).strict()).max(20_000),
  blobs: z.array(z.object({ sha: sha40, content: z.string() }).strict()).max(5_000),
}).strict();
export type SyncPushRequest = z.infer<typeof syncPushRequest>;
/** The slice of the GitHub client the guarded push uses; `GitHub` satisfies it. */
export interface GitDataApi { config: { base: string }; request(path: string, method?: string, body?: unknown): Promise<any> }

/**
 * The workflow paths a sync commit changes against the base it merged. GitHub's create-tree API
 * applies an entry at a directory path to that whole subtree, so `.github/workflows` itself and its
 * ancestors (`.github`) count as workflow changes too, whatever the entry's sha, mode or type.
 */
const touchesWorkflows = (path: string) => path.startsWith(workflowsDirectory) || workflowsDirectory.startsWith(`${path}/`);
export const workflowPaths = (entries: readonly { path: string }[]) => entries.map(entry => entry.path).filter(touchesWorkflows).sort();
/** A file-level path as `git diff-tree -r` writes it: no empty, `.` or `..` segment that GitHub might resolve elsewhere. */
const fileLevelPath = (path: string) => path.split('/').every(segment => segment !== '' && segment !== '.' && segment !== '..');
export function workflowSyncRefusal(input: { request: Pick<SyncPushRequest, 'commit' | 'parents' | 'entries'>; branch: string; baseBranch: string; branchHead: string | null; baseContains: boolean; plannedFiles: string[] }): string | null {
  const { request, branch, baseBranch, branchHead, baseContains, plannedFiles } = input;
  const commit = request.commit.slice(0, 12);
  if (request.parents.length !== 2) return `${commit} is not a base sync: it has ${request.parents.length} parent${request.parents.length === 1 ? '' : 's'}, and only the two-parent merge of origin/${baseBranch} into ${branch} is pushed by the control plane`;
  if (!branchHead) return `${branch} does not exist on GitHub; push the branch's own commits first, then ask for the base sync`;
  if (request.parents[0] !== branchHead) return `${commit} does not fast-forward ${branch}: its first parent is ${request.parents[0].slice(0, 12)} but the branch is at ${branchHead.slice(0, 12)}; push the branch's own commits first with a plain git push, then ask again`;
  if (!baseContains) return `${commit} does not merge origin/${baseBranch}: its second parent ${request.parents[1].slice(0, 12)} is not in origin/${baseBranch}`;
  const malformed = request.entries.map(entry => entry.path).filter(path => !fileLevelPath(path));
  if (malformed.length) return `${commit} lists entries that are not file-level paths, so the workflow guard cannot judge them: ${malformed.join(', ')}`;
  // A directory-level entry replaces or deletes every workflow file at once: never a pure base sync, plannedFiles or not.
  const differing = workflowPaths(request.entries).filter(path => !path.startsWith(workflowsDirectory) || !inPlannedScope(plannedFiles, path));
  if (differing.length) return `${commit} changes workflow files beyond origin/${baseBranch} outside plannedFiles, so it is not a pure base sync: ${differing.join(', ')}`;
  return null;
}

/**
 * Rebuilds the named commit on GitHub and moves the branch to it without force: the blobs the
 * worker sent, the base parent's tree with the listed entries applied, then the commit itself with
 * its own message, people, parents and signature. A rebuilt tree or commit that is not the named
 * one is refused — nothing is pushed that the worker did not commit, and nothing the guard did not see.
 */
export async function pushWorkflowSync(github: GitDataApi, branch: string, request: SyncPushRequest): Promise<void> {
  const short = request.commit.slice(0, 12);
  for (const blob of request.blobs) {
    const created = await github.request('/git/blobs', 'POST', { content: blob.content, encoding: 'base64' });
    demand(created?.sha === blob.sha, `GitHub stored a blob of ${short} as ${String(created?.sha).slice(0, 12)}, not ${blob.sha.slice(0, 12)}`, 422);
  }
  const baseTree = (await github.request(`/git/commits/${request.parents[1]}`))?.tree?.sha;
  demand(typeof baseTree === 'string', `GitHub did not return the tree of ${request.parents[1].slice(0, 12)}`, 502);
  const tree = request.entries.length ? (await github.request('/git/trees', 'POST', { base_tree: baseTree, tree: request.entries }))?.sha : baseTree;
  demand(tree === request.tree, `The base tree with the listed entries is ${String(tree).slice(0, 12)}, not the tree ${request.tree.slice(0, 12)} of ${short}; the entries do not describe the commit`, 422);
  const commit = await github.request('/git/commits', 'POST', { message: request.message, tree, parents: request.parents, author: request.author, committer: request.committer, ...(request.signature ? { signature: request.signature } : {}) });
  demand(commit?.sha === request.commit, `GitHub rebuilt ${short} as ${String(commit?.sha).slice(0, 12)}; the commit cannot be reproduced exactly, so nothing was pushed`, 422);
  await github.request(`/git/refs/heads/${branch.split('/').map(encodeURIComponent).join('/')}`, 'PATCH', { sha: request.commit, force: false });
}

/** Where the request may push: the requesting worker's own workspace branch for the leased epoch. */
export interface SyncPushOutcome { key: string; epoch: number; worker: string; branch: string; baseBranch: string; commit: string; from: string; base: string; workflowPaths: string[]; pushed: true }
/**
 * `graphyard sync GY-N --push-via-control-plane COMMIT`, server side: the lease holder only, its
 * own assigned branch only. Every outcome is appended to the item's history attributed to the
 * requesting worker and epoch — `sync.workflow-push` when pushed, `sync.workflow-push.refused`
 * with the reason otherwise.
 */
export async function controlPlaneSyncPush(services: { engine: { store: Store }; github: GitDataApi | null }, actor: Principal, id: string, input: unknown, now = new Date()): Promise<SyncPushOutcome> {
  demand(actor.role === 'worker', 'Only the worker holding the item\'s lease may ask the control plane to push its base sync', 403);
  const parsed = syncPushRequest.safeParse(input);
  demand(parsed.success, `A sync push request names the epoch and the commit as graphyard sync --push-via-control-plane sends them: ${parsed.success ? '' : parsed.error.issues.map(issue => `${issue.path.join('.')}: ${issue.message}`).join('; ')}`, 422);
  const request = parsed.data;
  const work = (await services.engine.store.list()).find(item => item.id === id || item.key === id);
  demand(work, 'Work not found', 404);
  activeLease(work, actor, request.epoch, now);
  demand(work.submission?.epoch !== request.epoch, `${work.key} epoch ${request.epoch} was submitted; its attempt pushes nothing more`);
  const workspace = work.workspaces.find(entry => entry.owner === actor.id && entry.epoch === request.epoch);
  demand(workspace, `${work.key} records no workspace branch for ${actor.id} epoch ${request.epoch}`, 422);
  demand(services.github, 'GitHub integration is required for the control plane to push a base sync', 503);
  const github = services.github, branch = workspace.branch, baseBranch = github.config.base;
  const record = (kind: string, payload: Record<string, unknown>) => services.engine.store.transaction(async (db, at) => {
    await db.query('INSERT INTO events(work_id,actor,kind,payload) VALUES($1,$2,$3,$4)', [work.id, actor.id, kind, JSON.stringify({ worker: actor.id, epoch: request.epoch, branch, baseBranch, commit: request.commit, ...payload, at: at.toISOString() })]);
  });
  const branchHead = await github.request(`/git/ref/heads/${branch.split('/').map(encodeURIComponent).join('/')}`).then((ref: any) => typeof ref?.object?.sha === 'string' ? ref.object.sha as string : null, (error: unknown) => {
    if (/\(404\)/.test(error instanceof Error ? error.message : String(error))) return null;
    throw error;
  });
  let baseContains = false;
  if (request.parents.length === 2 && request.parents[0] === branchHead) {
    const status = (await github.request(`/compare/${request.parents[1]}...${encodeURIComponent(baseBranch)}`))?.status;
    baseContains = status === 'ahead' || status === 'identical';
  }
  const refusal = workflowSyncRefusal({ request, branch, baseBranch, branchHead, baseContains, plannedFiles: work.plannedFiles ?? [] });
  if (refusal) {
    await record('sync.workflow-push.refused', { reason: refusal, workflowPaths: workflowPaths(request.entries) });
    demand(false, refusal, 422);
  }
  try { await pushWorkflowSync(github, branch, request); }
  catch (error) {
    await record('sync.workflow-push.refused', { reason: error instanceof Error ? error.message : String(error), workflowPaths: workflowPaths(request.entries) });
    throw error;
  }
  const outcome: SyncPushOutcome = { key: work.key, epoch: request.epoch, worker: actor.id, branch, baseBranch, commit: request.commit, from: request.parents[0], base: request.parents[1], workflowPaths: workflowPaths(request.entries), pushed: true };
  await record('sync.workflow-push', { from: outcome.from, base: outcome.base, workflowPaths: outcome.workflowPaths });
  return outcome;
}
