import type { ScopeFile, Work } from './model.js';
import { classifyScope, inPlannedScope, shippedBy, type ScopeFinding } from './regression-guard.js';

/**
 * Local half of the regression guard, for `graphyard sync`. Parses `git diff --raw -M -z
 * --no-abbrev BASE HEAD` and `git diff --numstat -M -z BASE HEAD`, both taken directly against
 * the fetched base tip, into the same file records the control plane derives from the provider.
 * Every record here already differs from the base tip; the classifier decides which are allowed.
 */
const statuses: Record<string, ScopeFile['status']> = { A: 'added', D: 'removed', M: 'modified', R: 'renamed', C: 'copied', T: 'changed' };
const zero = /^0+$/;
export function parseLocalScopeDiff(raw: string, numstat: string): ScopeFile[] {
  const counts = new Map<string, { additions: number; deletions: number; binary: boolean }>();
  const numstatTokens = numstat.split('\0');
  for (let i = 0; i < numstatTokens.length; i++) {
    const match = numstatTokens[i].match(/^(\d+|-)\t(\d+|-)\t(.*)$/s);
    if (!match) continue;
    const binary = match[1] === '-';
    // A rename carries an empty path followed by the old and new paths as separate tokens.
    const path = match[3] !== '' ? match[3] : numstatTokens[(i += 2)];
    counts.set(path, { additions: binary ? 0 : Number(match[1]), deletions: binary ? 0 : Number(match[2]), binary });
  }
  const files: ScopeFile[] = [];
  const tokens = raw.split('\0');
  for (let i = 0; i < tokens.length; i++) {
    const header = tokens[i].match(/^:(\d+) (\d+) ([0-9a-f]+) ([0-9a-f]+) ([A-Z])\d*$/);
    if (!header) continue;
    const [, , , oldSha, newSha, code] = header;
    const status = statuses[code] ?? 'modified';
    const moved = code === 'R' || code === 'C';
    const previousPath = moved ? tokens[++i] : undefined;
    const path = tokens[++i];
    const count = counts.get(path) ?? { additions: 0, deletions: 0, binary: false };
    const file: ScopeFile = { path, status, sha: zero.test(newSha) ? null : newSha, additions: count.additions, deletions: count.deletions, binary: count.binary,
      // The diff is against the base tip itself: the old side is exactly what the base holds.
      baseSha: moved ? null : zero.test(oldSha) ? null : oldSha };
    if (previousPath) { file.previousPath = previousPath; file.previousBaseSha = zero.test(oldSha) ? null : oldSha; }
    files.push(file);
  }
  return files;
}

export function localScopeFindings(plannedFiles: string[], raw: string, numstat: string, generated: readonly string[] = []): ScopeFinding[] {
  return classifyScope(plannedFiles, parseLocalScopeDiff(raw, numstat), generated);
}

/**
 * Generated files a repository declares for `graphyard sync`: the manifest `scripts/check-docs.mjs
 * --manifest` prints — the exact paths its `--write` renders in full. A repository without the
 * script declares none, and sync regenerates nothing.
 */
export interface GeneratedManifest { files: string[]; regenerate: string[] }
export function parseGeneratedManifest(output: string): GeneratedManifest | null {
  try {
    const parsed = JSON.parse(output);
    const files = Array.isArray(parsed?.generated) ? parsed.generated.filter((entry: unknown): entry is string => typeof entry === 'string' && !!entry) : [];
    const regenerate = typeof parsed?.regenerate === 'string' ? parsed.regenerate.split(/\s+/).filter(Boolean) : [];
    return files.length && regenerate.length ? { files, regenerate } : null;
  } catch { return null; }
}

/** Lines git leaves in a file it could not merge. */
export const hasConflictMarkers = (text: string) => /^(<{7}|={7}|>{7}|\|{7})( |$)/m.test(text);

/**
 * The managed `AGENTS.md` blocks are generated by `graphyard init` and `master init`, so a merge
 * conflict inside them is resolved by rendering the blocks afresh around the hand-written text.
 * A conflict that reaches outside the blocks — or one that duplicates the block markers, which
 * the renderers refuse as malformed — is left for the worker; nothing is guessed.
 */
export function regenerateManagedBlocks(conflicted: string, render: (text: string) => string): string | null {
  try {
    const rendered = render(conflicted);
    return hasConflictMarkers(rendered) ? null : rendered;
  } catch { return null; }
}
export const managedServerUrl = (text: string) => text.match(/uses Graphyard at (\S+) for ownership/)?.[1] ?? null;

/**
 * Which shipped work each remaining conflict comes from: the delivered items whose merge commit
 * the sync brings in and whose planned scope or observed diff covers the path. When none of the
 * newly landed items covers it, every delivered item that ever shipped the path is named instead.
 */
export function attributeConflicts(paths: string[], all: Work[], landed: (sha: string) => boolean, generated: readonly string[] = []) {
  const arrived = all.filter(item => item.stage === 'done' && [item.delivery?.mergeSha, item.observation?.mergeSha].some(sha => !!sha && landed(sha)));
  return paths.map(path => {
    const covers = (item: Work) => inPlannedScope(item.plannedFiles ?? [], path) || (item.observation?.files ?? []).includes(path);
    const causes = arrived.filter(covers).map(item => item.key);
    return { path, generated: generated.includes(path), shippedBy: causes.length ? causes : shippedBy(path, all), landedSince: causes.length > 0 };
  });
}
