import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { stages, type Work, type Stage } from '../src/model';
import './style.css';
import Docs from './docs';
import ScenarioLibrary from './scenarios';
import { assignment } from './assignment';

function age(time: string) { const minutes = Math.max(0, Math.floor((Date.now() - Date.parse(time)) / 60000)); return minutes < 60 ? `${minutes}m` : `${Math.floor(minutes / 60)}h ${minutes % 60}m`; }
function App() {
  const [token, setToken] = useState(sessionStorage.getItem('graphyard-token') ?? '');
  const [draftToken, setDraftToken] = useState('');
  const [work, setWork] = useState<Work[]>([]);
  const [status, setStatus] = useState<any>(null);
  const [error, setError] = useState('');
  const [view, setView] = useState('graph');
  const [filter, setFilter] = useState<Stage | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [events, setEvents] = useState<any[]>([]);
  const [creating, setCreating] = useState(false);
  const [busy, setBusy] = useState(false);
  const [query, setQuery] = useState('');
  async function api(path: string, data?: unknown) {
    const response = await fetch(`/api/${path}`, { method: data === undefined ? 'GET' : 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() }, body: data === undefined ? undefined : JSON.stringify(data) });
    const body = await response.json(); if (!response.ok) throw new Error(body.error + (body.issues ? `: ${body.issues.map((i: any) => i.message).join(', ')}` : '')); return body;
  }
  async function refresh() { const [items, system] = await Promise.all([api('work'), api('status')]); setWork(items); setStatus(system); setError(''); }
  useEffect(() => { if (!token) return; let active = true; const load = () => refresh().catch(e => { if (active) setError(e.message); }); void load(); const timer = setInterval(load, 5000); return () => { active = false; clearInterval(timer); }; }, [token]);
  useEffect(() => { if (selected) void api(`events?work=${selected}`).then(setEvents).catch(e => setError(e.message)); }, [selected, work]);
  const item = work.find(w => w.id === selected);
  const visible = work.filter(w => (!filter || w.stage === filter) && `${w.key} ${w.title}`.toLowerCase().includes(query.toLowerCase()));
  const blocked = work.filter(w => w.blocker || w.submission && w.gates.some(g => !g.passed));
  const active = work.filter(w => w.lease && Date.parse(w.lease.expiresAt) > Date.now());
  async function action(id: string, command: string, data: unknown = {}) { setBusy(true); try { await api(`work/${id}/${command}`, data); await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (!token) return <main className="login"><div className="brand"><span className="mark">g</span> graphyard</div><h1>Keep the work<br/>moving forward.</h1><p>One place for ownership, evidence, and delivery.</p><form onSubmit={e => { e.preventDefault(); sessionStorage.setItem('graphyard-token', draftToken); setToken(draftToken); }}><label>Access token<input type="password" required value={draftToken} onChange={e => setDraftToken(e.target.value)} autoComplete="off" placeholder="Your Graphyard token"/></label><button>Open control plane ↗</button></form><small>Tokens are scoped to your role and kept for this browser session.</small></main>;
  const card = (w: Work) => <button className={`card ${w.violations.length ? 'violation' : ''}`} key={w.id} onClick={() => setSelected(w.id)}><div className="card-top"><span>{w.key}</span><span>P{w.priority} · {age(w.stageEnteredAt)}</span></div><h3>{w.title}</h3><div className="card-meta"><span className={`dot ${assignment(w).active ? 'green' : ''}`}/><span title={assignment(w).owner ? `Worker ID: ${assignment(w).owner}` : undefined}>{assignment(w).text}</span><span className="push">{w.candidate ? `#${w.candidate.pr}` : 'No PR'}</span></div>{w.gates.find(g => !g.passed) && <p className="reason">{w.gates.find(g => !g.passed)!.reasons[0]}</p>}</button>;
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="mark">g</span> graphyard</div><div className="workspace-label">CONTROL PLANE</div><button className={view === 'graph' ? 'nav active' : 'nav'} onClick={() => setView('graph')}>⌘ <span>Delivery graph</span></button><button className={view === 'board' ? 'nav active' : 'nav'} onClick={() => setView('board')}>▥ <span>Work board</span><small>{work.length}</small></button><button className={view === 'scenarios' ? 'nav active' : 'nav'} onClick={() => setView('scenarios')}>✓ <span>Test cases</span></button><a className="nav" href="/docs">↗ <span>Documentation</span></a><div className="sidebar-bottom"><span className={`dot ${status ? 'green' : ''}`}/>{status ? 'Control plane connected' : 'Connecting…'}<p>{status?.actor?.id}</p><button className="text-button" onClick={() => { sessionStorage.removeItem('graphyard-token'); setToken(''); setStatus(null); }}>Sign out</button></div></aside>
    <main className="main">{view === 'scenarios' ? <ScenarioLibrary api={api} canEdit={status?.actor?.role === 'admin'}/> : <><header><div className="breadcrumb">Workspace <span>/</span> {status?.repository ?? 'Graphyard'}</div><div className="live"><span className="dot green"/> Refreshes every 5s</div></header>
      <div className="page-heading"><div><div className="eyebrow">ENGINEERING, IN VIEW</div><h1>{view === 'graph' ? 'Delivery graph' : 'Work board'}</h1><p>Every change has an owner. Every transition needs proof.</p></div>{status?.actor?.role === 'admin' && <button onClick={() => setCreating(true)}>＋ New work item</button>}</div>
      {error && <div role="alert" className="notice danger">{error}</div>}
      {!status?.github && <div className="notice">GitHub enforcement is not connected. Work can be coordinated; merge gates remain closed. <a href="/docs/github">Setup guide ↗</a></div>}
      {status?.jobs?.length > 0 && <div className="notice danger">{status.jobs.length} integration job(s) need attention: {status.jobs[0].error}</div>}
      <div className="metrics"><div><span>Open work</span><strong>{work.filter(w => w.stage !== 'done').length}</strong><small>Across the delivery graph</small></div><div><span>Active assignments</span><strong>{active.length}<i className="dot green"/></strong><small>{new Set(active.flatMap(w => w.workspaces.filter(s => s.epoch === w.epoch).map(s => s.host))).size} registered machines</small></div><div><span>Awaiting evidence</span><strong className="amber">{blocked.length}</strong><small>Explicit reasons, actionable next steps</small></div><div><span>Delivered</span><strong>{work.filter(w => w.stage === 'done').length}</strong><small>Observed merge · verified gates</small></div></div>
      {view === 'graph' && <section className="graph-section"><div className="section-title"><h2>From intent to delivery</h2><span>SELECT A STAGE TO INSPECT</span></div><div className="graph">{stages.map((stage, i) => { const items = work.filter(w => w.stage === stage); const dwell = items.map(w => Date.now() - Date.parse(w.stageEnteredAt)).sort((a, b) => a - b); return <React.Fragment key={stage}>{i > 0 && <span className="connector">→</span>}<button className={`node ${filter === stage ? 'selected' : ''} ${items.some(w => w.submission && w.gates.some(g => !g.passed)) ? 'waiting' : ''}`} onClick={() => setFilter(filter === stage ? null : stage)}><span>{stage}</span><strong>{items.length}</strong><small>{items.length ? `Oldest ${age(items.reduce((a, b) => a.stageEnteredAt < b.stageEnteredAt ? a : b).stageEnteredAt)}` : 'Clear'}</small><small>{dwell.length ? `p50 ${Math.floor(dwell[Math.floor(dwell.length * .5)] / 60000)}m · p95 ${Math.floor(dwell[Math.min(dwell.length - 1, Math.floor(dwell.length * .95))] / 60000)}m` : '—'}</small></button></React.Fragment>; })}</div><p className="graph-note"><span className="dot amber-bg"/> Items appear at their first refusing gate. Dwell measures current time in stage.</p></section>}
      <section><div className="section-title"><h2>{filter ? `${filter[0].toUpperCase()}${filter.slice(1)} work` : 'Work ledger'} <span className="count">{visible.length}</span></h2><div className="filters">{filter && <button className="text-button" onClick={() => setFilter(null)}>Clear filter ×</button>}<input aria-label="Search work" placeholder="Search work…" value={query} onChange={e => setQuery(e.target.value)}/></div></div>
      {work.length === 0 ? <div className="empty"><span>◇</span><h2>Your delivery graph starts with intent.</h2><p>Create a work item, define what proves it works,<br/>and let an agent claim the implementation.</p>{status?.actor?.role === 'admin' && <button onClick={() => setCreating(true)}>Create the first work item</button>}</div> : view === 'board' ? <div className="board">{stages.filter(s => !filter || filter === s).map(s => <div className="column" key={s}><h3>{s} <span>{visible.filter(w => w.stage === s).length}</span></h3>{visible.filter(w => w.stage === s).map(card)}</div>)}</div> : <div className="cards">{visible.map(card)}</div>}</section>
      <footer>Graphyard <span>Ownership is explicit. Evidence drives progression.</span></footer></>}
    </main>
    {item && <div className="overlay" onClick={() => setSelected(null)}><section role="dialog" aria-modal="true" aria-label={item.title} className="drawer" onClick={e => e.stopPropagation()}><button className="close" aria-label="Close details" onClick={() => setSelected(null)}>×</button><div className="eyebrow">{item.key} / {item.type}</div><h2>{item.title}</h2><p>{item.description}</p><div className="tags"><span>{item.stage}</span><span>Policy v{item.policyRevision}</span><span>Revision {item.revision}</span></div>{item.violations.map(v => <div className="notice danger" key={v}>{v}</div>)}<h3>Ownership</h3><p>{assignment(item).text}</p>{assignment(item).owner && <p className="muted">Worker ID: {assignment(item).owner} · assignment {assignment(item).epoch}</p>}<p>{assignment(item).active && item.lease ? `Active lease · expires ${new Date(item.lease.expiresAt).toLocaleTimeString()}` : 'No active assignment'}</p>{item.workspaces.map(w => <code key={w.epoch}>{w.host}:{w.path}<br/>{w.branch} · assignment {w.epoch}</code>)}{item.candidate && <p>PR #{item.candidate.pr} · <code>{item.candidate.sha.slice(0, 12)}</code></p>}
      <h3>Gate decisions</h3>{item.gates.map(g => <div className="gate" key={g.name}><strong className={g.passed ? 'green-text' : 'amber'}>{g.passed ? '✓' : '○'} {g.name}</strong>{g.reasons.map(r => <p key={r}>{r}</p>)}</div>)}<h3>Acceptance criteria</h3>{item.criteria.map(ac => <div className="criterion" key={ac.id}><strong>{ac.id} · {ac.text}</strong><p>{ac.proofs.join(' + ')}</p></div>)}<h3>Evidence ({item.evidence.length})</h3>{item.evidence.map(e => <div className="criterion" key={e.id}><strong>{e.result === 'pass' ? '✓' : '×'} {e.proof}</strong><p>{e.trusted ? 'Trusted producer' : 'Worker assertion'} · {e.producer} · {e.sha.slice(0, 8)} · {e.executed} executed / {e.skipped} skipped</p></div>)}
      <h3>History</h3><div className="timeline">{events.map(e => <div key={e.seq}><span>{new Date(e.created_at).toLocaleString()}</span><strong>{e.kind}</strong><small>{e.actor}</small></div>)}</div>{!item.ready && status?.actor?.role === 'admin' && <button disabled={busy} onClick={() => action(item.id, 'ready')}>Release to ready</button>}</section></div>}
    {creating && <div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="New work item"><button className="close" aria-label="Close form" onClick={() => setCreating(false)}>×</button><div className="eyebrow">DEFINE THE OUTCOME</div><h2>New work item</h2><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); try { const created = await api('work', { title: f.get('title'), description: f.get('description'), criteria: [{ id: 'AC-1', text: f.get('criterion'), proofs: [f.get('proof')] }], dependencies: f.get('dependency') ? [f.get('dependency')] : [], policy: { review: true, checks: String(f.get('checks')).split(',').map(s => s.trim()).filter(Boolean) } }); setCreating(false); await refresh(); setSelected(created.id); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><label>Title<input name="title" required maxLength={200} placeholder="What needs to change?"/></label><label>Description<textarea name="description" rows={3}/></label><label>Acceptance criterion<input name="criterion" required placeholder="What observable behavior proves success?"/></label><label>Required proof<input name="proof" required pattern="(unit|integration|e2e|manual):[a-zA-Z0-9._/-]+" placeholder="integration:claim-safety"/></label><label>Required CI checks<input name="checks" defaultValue="test, typecheck" required/></label><label>Depends on<select name="dependency"><option value="">No dependency</option>{work.map(w => <option key={w.id} value={w.id}>{w.key} · {w.title}</option>)}</select></label><p className="muted">Created in backlog. Independent review is required. Use the CLI to define multiple criteria or dependencies.</p>{error && <p role="alert" className="amber">{error}</p>}<button disabled={busy}>{busy ? 'Creating…' : 'Create work item'}</button></form></section></div>}
  </div>;
}
createRoot(document.getElementById('root')!).render(location.pathname.startsWith('/docs') ? <Docs/> : <App/>);
