import { useEffect, useState, useRef } from 'react';
import Dialog from './dialog';
import Term from './components/term';
import type { Scenario } from '../src/scenarios';

type Draft = Omit<Scenario, 'revision' | 'hash' | 'createdAt' | 'createdBy'> & { expectedRevision: number };
const empty: Draft = { id: '', title: '', purpose: '', setup: [], steps: [], expected: [], environment: 'staging', runner: 'Playwright', testPath: '', expectedRevision: 0 };
export default function ScenarioLibrary({ api, canEdit }: { api: (path: string, data?: unknown) => Promise<any>; canEdit: boolean }) {
  const [items, setItems] = useState<Scenario[]>([]);
  const [draft, setDraft] = useState<typeof empty | null>(null);
  const [loadError, setLoadError] = useState('');
  const [formError, setFormError] = useState('');
  const [busy, setBusy] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [loading, setLoading] = useState(true);
  const request = useRef(0);
  const load = async () => {
    const version = ++request.current; setLoading(true); setLoadError('');
    try { const rows = await api('scenarios'); if (version === request.current) { setItems(rows); setLoaded(true); } }
    catch (e) { if (version === request.current) setLoadError((e as Error).message); }
    finally { if (version === request.current) setLoading(false); }
  };
  useEffect(() => { void load(); return () => { request.current++; }; }, []);
  const latest = items.filter((s, i) => items.findIndex(x => x.id === s.id) === i);
  function open(next: typeof empty | null) { setFormError(''); setDraft(next); }
  function edit(s: Scenario) { open({ id: s.id, title: s.title, purpose: s.purpose, setup: s.setup, steps: s.steps, expected: s.expected, environment: s.environment, runner: s.runner, testPath: s.testPath, expectedRevision: s.revision }); }
  return <><header><div className="breadcrumb">Verification <span>/</span> <Term term="end-to-end test">E2E</Term> <Term term="test case">test cases</Term></div><a href="/docs/validation#test-cases">Read the guide ↗</a></header><div className="page-heading"><div><div className="eyebrow">DEFINE WHAT WORKING MEANS</div><h1>Test-case library</h1><p>Versioned scenarios. Explicit outcomes. Execution backed by evidence.</p></div>{canEdit && <button onClick={() => open(empty)}>＋ New test case</button>}</div>{loadError && <div role="alert" className="notice danger">{loadError} <button disabled={loading} onClick={() => void load()}>Retry loading test cases</button>{loaded && (latest.length ? <p>Previously loaded definitions are shown; they may be stale.</p> : <p>The library could not be re-read; its current contents are unknown.</p>)}</div>}<div className="notice">Definitions live here; executable tests stay in Git. Work items pin the scenario version and environment they require. Defining a case does not run it.</div>
    {loading && <p role="status">Loading test cases…</p>}{!loaded ? (!loading && <p>Test cases could not be loaded. Retry to observe the library.</p>) : !latest.length && !loading ? (loadError ? <p>Test cases could not be re-read. Retry to observe the library.</p> : <div className="empty"><span>◇</span><h2>Describe the behavior you need to prove.</h2><p>Add the setup, steps, expected results, and test runner.<br/>Then link the scenario to an acceptance criterion.</p>{canEdit && <button onClick={() => open(empty)}>Define the first test case</button>}</div>) : <div className="scenario-list">{latest.map(s => <article className="scenario-card" key={s.id}><div className="card-top"><span><Term term="end-to-end test">e2e:</Term>{s.id}</span><span>v{s.revision} · {s.environment}</span></div><h2>{s.title}</h2><p>{s.purpose}</p><div className="scenario-columns"><div><h3>Setup</h3><ul>{s.setup.map((line, i) => <li key={i}>{line}</li>)}</ul><h3>Steps</h3><ol>{s.steps.map((line, i) => <li key={i}>{line}</li>)}</ol></div><div><h3>Expected results</h3><ul>{s.expected.map((line, i) => <li key={i}>{line}</li>)}</ul><h3>Executable test</h3><p>{s.runner}</p><code>{s.testPath}</code></div></div><details><summary>Version history · {items.filter(x => x.id === s.id).length} version(s)</summary>{items.filter(x => x.id === s.id).map(x => <div className="criterion" key={x.revision}><strong>v{x.revision} · {new Date(x.createdAt).toLocaleString()} · {x.createdBy}</strong><p>{x.purpose}</p><p>Expected: {x.expected.join('; ')}</p><code>{x.hash}</code></div>)}</details>{canEdit && <button className="text-button" onClick={() => edit(s)}>Publish a new version ↗</button>}</article>)}</div>}
    {draft && <Dialog onClose={() => open(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Define E2E test case"><button className="close" aria-label="Close form" onClick={() => open(null)}>×</button><h2>{draft.expectedRevision ? `Publish version ${draft.expectedRevision + 1}` : <>Define an <Term term="end-to-end test">E2E</Term> <Term term="test case">test case</Term></>}</h2><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const lines = (name: string) => String(f.get(name)).split('\n').map(s => s.trim()).filter(Boolean); setBusy(true); setFormError(''); try { await api('scenarios', { id: f.get('id'), title: f.get('title'), purpose: f.get('purpose'), setup: lines('setup'), steps: lines('steps'), expected: lines('expected'), environment: f.get('environment'), runner: f.get('runner'), testPath: f.get('testPath'), expectedRevision: draft.expectedRevision }); open(null); await load(); } catch (e) { setFormError((e as Error).message); } finally { setBusy(false); } }}><label>Stable ID<input name="id" defaultValue={draft.id} readOnly={!!draft.expectedRevision} required pattern="[a-z0-9][a-z0-9._-]*" placeholder="confirmed-booking-sends-sms"/></label><label>Title<input name="title" defaultValue={draft.title} required/></label><label>Purpose<textarea name="purpose" defaultValue={draft.purpose} required rows={2}/></label><label>Setup — one condition per line<textarea name="setup" defaultValue={draft.setup.join('\n')} rows={2}/></label><label>Steps — one action per line<textarea name="steps" defaultValue={draft.steps.join('\n')} required rows={3}/></label><label>Expected results — one assertion per line<textarea name="expected" defaultValue={draft.expected.join('\n')} required rows={3}/></label><label>Target environment<input name="environment" defaultValue={draft.environment} required/></label><label>Runner<input name="runner" defaultValue={draft.runner} required/></label><label>Test file in Git<input name="testPath" defaultValue={draft.testPath} placeholder="tests/e2e/booking-sms.spec.ts" required/></label><p className="muted">Publishing preserves previous versions. Existing work keeps its pinned requirement.</p>{formError && <p className="amber" role="alert">{formError}</p>}<button disabled={busy}>{busy ? 'Publishing…' : 'Publish test case'}</button></form></section></Dialog>}
  </>;
}
