import { useEffect, useState } from 'react';
import Dialog from './dialog';
import type { Scenario } from '../src/scenarios';

type Draft = Omit<Scenario, 'revision' | 'hash' | 'createdAt' | 'createdBy'> & { expectedRevision: number };
const empty: Draft = { id: '', title: '', purpose: '', setup: [], steps: [], expected: [], environment: 'staging', runner: 'Playwright', testPath: '', expectedRevision: 0 };
export default function ScenarioLibrary({ api, canEdit }: { api: (path: string, data?: unknown) => Promise<any>; canEdit: boolean }) {
  const [items, setItems] = useState<Scenario[]>([]);
  const [draft, setDraft] = useState<typeof empty | null>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const load = () => api('scenarios').then(setItems).catch(e => setError(e.message));
  useEffect(() => { void load(); }, []);
  const latest = items.filter((s, i) => items.findIndex(x => x.id === s.id) === i);
  function edit(s: Scenario) { setDraft({ id: s.id, title: s.title, purpose: s.purpose, setup: s.setup, steps: s.steps, expected: s.expected, environment: s.environment, runner: s.runner, testPath: s.testPath, expectedRevision: s.revision }); }
  return <><header><div className="breadcrumb">Verification <span>/</span> E2E test cases</div><a href="/docs/test-cases">Read the guide ↗</a></header><div className="page-heading"><div><div className="eyebrow">DEFINE WHAT WORKING MEANS</div><h1>Test-case library</h1><p>Versioned scenarios. Explicit outcomes. Execution backed by evidence.</p></div>{canEdit && <button onClick={() => setDraft(empty)}>＋ New test case</button>}</div>{error && <div role="alert" className="notice danger">{error}</div>}<div className="notice">Definitions live here; executable tests stay in Git. Work items pin the scenario version and environment they require. Defining a case does not run it.</div>
    {!latest.length ? <div className="empty"><span>◇</span><h2>Describe the behavior you need to prove.</h2><p>Add the setup, steps, expected results, and test runner.<br/>Then link the scenario to an acceptance criterion.</p>{canEdit && <button onClick={() => setDraft(empty)}>Define the first test case</button>}</div> : <div className="scenario-list">{latest.map(s => <article className="scenario-card" key={s.id}><div className="card-top"><span>e2e:{s.id}</span><span>v{s.revision} · {s.environment}</span></div><h2>{s.title}</h2><p>{s.purpose}</p><div className="scenario-columns"><div><h3>Setup</h3><ul>{s.setup.map((line, i) => <li key={i}>{line}</li>)}</ul><h3>Steps</h3><ol>{s.steps.map((line, i) => <li key={i}>{line}</li>)}</ol></div><div><h3>Expected results</h3><ul>{s.expected.map((line, i) => <li key={i}>{line}</li>)}</ul><h3>Executable test</h3><p>{s.runner}</p><code>{s.testPath}</code></div></div><details><summary>Version history · {items.filter(x => x.id === s.id).length} version(s)</summary>{items.filter(x => x.id === s.id).map(x => <div className="criterion" key={x.revision}><strong>v{x.revision} · {new Date(x.createdAt).toLocaleString()} · {x.createdBy}</strong><p>{x.purpose}</p><p>Expected: {x.expected.join('; ')}</p><code>{x.hash}</code></div>)}</details>{canEdit && <button className="text-button" onClick={() => edit(s)}>Publish a new version ↗</button>}</article>)}</div>}
    {draft && <Dialog onClose={() => setDraft(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Define E2E test case"><button className="close" aria-label="Close form" onClick={() => setDraft(null)}>×</button><h2>{draft.expectedRevision ? `Publish version ${draft.expectedRevision + 1}` : 'Define an E2E test case'}</h2><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const lines = (name: string) => String(f.get(name)).split('\n').map(s => s.trim()).filter(Boolean); setBusy(true); try { await api('scenarios', { id: f.get('id'), title: f.get('title'), purpose: f.get('purpose'), setup: lines('setup'), steps: lines('steps'), expected: lines('expected'), environment: f.get('environment'), runner: f.get('runner'), testPath: f.get('testPath'), expectedRevision: draft.expectedRevision }); setDraft(null); setError(''); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><label>Stable ID<input name="id" defaultValue={draft.id} readOnly={!!draft.expectedRevision} required pattern="[a-z0-9][a-z0-9._-]*" placeholder="confirmed-booking-sends-sms"/></label><label>Title<input name="title" defaultValue={draft.title} required/></label><label>Purpose<textarea name="purpose" defaultValue={draft.purpose} required rows={2}/></label><label>Setup — one condition per line<textarea name="setup" defaultValue={draft.setup.join('\n')} rows={2}/></label><label>Steps — one action per line<textarea name="steps" defaultValue={draft.steps.join('\n')} required rows={3}/></label><label>Expected results — one assertion per line<textarea name="expected" defaultValue={draft.expected.join('\n')} required rows={3}/></label><label>Target environment<input name="environment" defaultValue={draft.environment} required/></label><label>Runner<input name="runner" defaultValue={draft.runner} required/></label><label>Test file in Git<input name="testPath" defaultValue={draft.testPath} placeholder="tests/e2e/booking-sms.spec.ts" required/></label><p className="muted">Publishing preserves previous versions. Existing work keeps its pinned requirement.</p>{error && <p className="amber" role="alert">{error}</p>}<button disabled={busy}>{busy ? 'Publishing…' : 'Publish test case'}</button></form></section></Dialog>}
  </>;
}
